### ISSUE TITLE
Call to undefined method Response::getStatus()

### ISSUE THREAD

**Issue by cpamaster** [raulr/google-play-scraper#35]
Found 2 problems:

```
In Client.php line 15:                                                
Call to undefined method Symfony\Component\BrowserKit\Response::getStatus()
```

```
In Scraper.php line 368:
Call to undefined method Symfony\Component\BrowserKit\Response::getStatus()
```

Need use getStatusCode()

**Comment by hcaz** [comment]
Related to #27

**Comment by pratikbarman** [comment]
Same Issue

**Comment by amilashanaka** [comment]
<br />
<b>Fatal error</b>: Uncaught Error: Call to undefined method Symfony\Component\BrowserKit\Response::getStatus() in
C:\wamp64\www\qrtrace\api\App_stat\vendor\raulr\google-play-scraper\src\Client.php:15
Stack trace:
#0 C:\wamp64\www\qrtrace\api\App_stat\vendor\symfony\browser-kit\AbstractBrowser.php(387):
Raulr\GooglePlayScraper\Client-&gt;filterResponse(Object(Symfony\Component\BrowserKit\Response))
#1 C:\wamp64\www\qrtrace\api\App_stat\vendor\raulr\google-play-scraper\src\Scraper.php(367):
Symfony\Component\BrowserKit\AbstractBrowser-&gt;request('GET', 'https://play.go...')
#2 C:\wamp64\www\qrtrace\api\App_stat\vendor\raulr\google-play-scraper\src\Scraper.php(108):
Raulr\GooglePlayScraper\Scraper-&gt;request('/store/apps/det...', Array)
#3 C:\wamp64\www\qrtrace\api\App_stat\andriod.php(13): Raulr\GooglePlayScraper\Scraper-&gt;getApp('com.mojang.mine...')
#4 {main}
thrown in <b>C:\wamp64\www\qrtrace\api\App_stat\vendor\raulr\google-play-scraper\src\Client.php</b> on line <b>15</b><br />

**Comment by SyedMuradAliShah** [comment]
- [Change getStatus() to getStatusCode() ] 

vendor\raulr\google-play-scraper\src\Client.php
Line: 15 
`$response->getStatus()`
to
`$response->getStatusCode()`

vendor\raulr\google-play-scraper\src\Scraper.php
Line: 368
`$status_code = $this->client->getResponse()->getStatus();`
to
`$status_code = $this->client->getResponse()->getStatusCode();`
